### ISSUE TITLE
Low range performance 

### ISSUE THREAD

**Issue by decosse** [abperiasamy/rtl8812AU_8821AU_linux#1]
I am using an Asus US-AC56 which also uses the Realtek driver 
However I discovered that the 4.2.2 has very limited range: if I am in direct line of sight of the router, it will work with high transfer rate - however if slightly removed (to adjacent room), it goes down considerably. 
i.e. with the device in the same physical location I can achieve ~ 45 Mbps (Internet Speed Test) in Windows vs 1-2 Mbps in Linux. But if I move to a closer proximity, the performance in Linux is comparable. 
Similarly, with the notebook in the same physical location, I get high transfer rate with the internal adapter in Linux, vs limited with the USB-AC56. 

Now - I notice on the Asus web-site, they have newer driver rev 4.2.5 available here:
http://support.asus.com/Download.aspx?SLanguage=en&m=USB-AC56&p=11&s=1
In the application notes is says 

> **Update MAC/BB/RF parameters and mechanism to improve overall performance**

so I believe this will address the range issue.

However the 4.2.5 will not load - the release says for Kernel support 2.6.18 ~ 3.10 - I am running 3.11. 

When tested in a kernel <3.10, the 4.2.5 driver definitely works MUCH better - has considerably improved speed when operated at a remote distance (the issue I was seeing with the 4.2.2) 

However will not work into 3.11 kernel. It appears to build and install however the USB adapter does not work and additionally it causes system errors once the driver is loaded (when the USB is plugged in) - the Terminal will not accept commands, the software manager nor driver updater will open, nor the file system and the system will not shut down - just hangs. 
So it definitely does not like to be used in 3.11 Kernel! 
However in 3.08 it installed and operates flawlessly and indeed also resolves the range issue. 

I can confirm I tested in Linux Mint 15 just using internet speed test as a quick reference:
Close line of sight proximity to router - 48 Mbps (55 peak) 
In another room (through walls etc) - 39 Mbps (44 peak)

With 4.2.2 build, in the same remote location as above, was only 1-2 Mbps (but same as 4.2.5 when close proximity)

**Summary  - 4.22 has a range issue - 4.2.5 definitely resolves the range/transfer rate issue however will not work in 3.11 kernel.** 

So - if you can work some magic on 4.2.5 to enable it run on the 3.11 kernel, that would be fantastic!

**Comment by Fredy72** [comment]
New version: v4.3.14_13455.20150212_BTCOEX20150128-51.
At https://github.com/Fredy72/rtl8821au, but I do not know how to run it.

**Comment by Braklet** [comment]
I just compiled and installed Fredy72's v4.3.14 driver on Ubuntu 12.04.5 and successfully ran it on an Edimax AC600 USB dongle.  All I can say at this point is that it seems to work well but I've tried no performance or stress tests.

First I edited the Makefile, disable POWER_SAVING (change from 'y' to 'n') then:

make
sudo make install
sudo modprobe 8821au

[Note that the above list doesn't include the changes I made to /etc/modprobe.d/blacklist.conf in order to bypass my other wireless drivers for this device.]

Thanks for the update, Fredy72!

**Comment by YYZ342** [comment]
I realize it's late coming to this post but hopefully it will help someone else. I was stuck trying to get Asus AC56R-1300 going on Cinnamon 17.3. The driver from 2014 worked! This is the one posted above by babuloseo on Dec 9, 2014 (today is Mar 7, 2016) lol and it worked like a charm on the first install: http://www.netis-systems.com/en/Downloads/Details/?id=904. I did not notice speed issues. Connection is 5Ghz and is strong one floor above the router (Asus RT-AC68U), opposite sides of the house. Thank you, babuloseo!!
Cheers.

**Comment by apcode** [comment]
The link given by babuloseo doesn't seem to work any more.  http://www.netis-systems.com/en/Downloads/Details/?id=904
Does anyone have a copy of that download? This repo doesn't work for me, I get low range and dropout. However the driver in that link works fine for me. I need to do a reinstall after a machine drive crash.

**Comment by Braklet** [comment]
Try this.  I'm not sure if it's the same target that used to be referenced by the netis-systems.com link, but I found it on my repo with the correct name:

https://www.dropbox.com/s/mcfso1iivpqkyar/netis%20WF2190%20Driver%20for%20Linux.rar?dl=0

Did you try Fredy72's repo version?  It's later than the Netis driver IIRC.  SAVE THAT RAR because my Dropbox link is only temporary.

Like you I experienced a system crash so I don't have any of my actual work on this device. :(  Right now I'm using my Edimax AC600 dongle on my Raspberry Pi B+ with whatever drivers came from OSMC and it's working fine.

**Comment by apcode** [comment]
Thanks Braklet.
I found an alternative and hopefully better solution. It seems that rtl8812au is now supported in ubuntu repos.

apt-get install rtl8812au-dkms

works now and it fixed all my problems. That is, the range issues are solved and the speed is near maximum.

Please note, I also have dkms installed before running the above install.

**Comment by harshavardhana** [comment]
Too old and stale closing
